# generated by datamodel-codegen:
#   filename:  angle.json
#   timestamp: 2023-04-28T09:01:10+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Angle(BaseModel):
    __root__: float = Field(..., description='Angular reading [deg]', title='Angle')
