# generated by datamodel-codegen:
#   filename:  pose.json
#   timestamp: 2023-04-28T09:01:10+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra

from . import attitude, position


class Pose(BaseModel):
    class Config:
        extra = Extra.forbid

    position: position.Position
    attitude: attitude.Attitude
