# generated by datamodel-codegen:
#   filename:  rpm.json
#   timestamp: 2023-04-28T09:01:10+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class RPM(BaseModel):
    __root__: float = Field(
        ..., description='RPM reading [Revolution Per Minute]', title='RPM'
    )
