# generated by datamodel-codegen:
#   filename:  speed.json
#   timestamp: 2023-04-28T09:01:10+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Speed(BaseModel):
    __root__: float = Field(..., description='Speed reading [knots]', title='Speed')
