# generated by datamodel-codegen:
#   filename:  wrench.json
#   timestamp: 2023-04-28T09:01:10+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra

from . import force, moment


class Wrench(BaseModel):
    class Config:
        extra = Extra.forbid

    force: force.Force
    moment: moment.Moment
